---
title: "Homework Assignment #3"
subtitle: "Exploring patterns of environmental justice"
author: "Joshua Mull"
date: last-modified
execute:
  warning: false
  message: false
format:
  html:
    toc: true
    code-fold: true
editor_options: 
  chunk_output_type: console
---


#### Load libraries 
```{r}
library(tidyverse)
library(sf)
library(stars)
library(terra)
library(zip)
library(tmap)
library(raster)
library(dplyr)
```

#### Read in data 
```{r, fig.width=10, fig.height=8}
# Use st_read to read in building data, save as variable building
building <-st_read(here::here("data", "gis_osm_buildings_a_free_1.gpkg"))

# Use st_read to read in road data, save as variable roads
roads <-st_read(here::here("data", "gis_osm_roads_free_1.gpkg"))

# Use rast from the terra package to read in tile h08v05 date 02/07/21, save as variable tile_8_5_07
tile_8_5_07 <- terra::rast(here::here("data", "VNP46A1", "VNP46A1.A2021038.h08v05.001.2021039064328.tif"))

# Use rast from the terra package to read in tile h08v06 date 02/07/21, save as variable tile_8_6_07
tile_8_6_07 <- terra::rast(here::here("data", "VNP46A1", "VNP46A1.A2021038.h08v06.001.2021039064329.tif"))

# Use rast from the terra package to read in tile h08v05 date 02/16/21, save as variable tile_8_5_16
tile_8_5_16 <- terra::rast(here::here("data", "VNP46A1", "VNP46A1.A2021047.h08v05.001.2021048091106.tif"))

# Use rast from the terra package to read in tile h08v06 date 02/16/21, save as variable tile_8_6_16
tile_8_6_16 <- terra::rast(here::here("data", "VNP46A1", "VNP46A1.A2021047.h08v06.001.2021048091105.tif"))

# Use st_read to read in income data
income <- st_read(here::here("data", "ACS_2019_5YR_TRACT_48_TEXAS.gdb"), layer = "X19_INCOME")

# Use st_read to read in road data, save as variable 
texas_cens <- st_read(here::here("data", "ACS_2019_5YR_TRACT_48_TEXAS.gdb"), layer = "ACS_2019_5YR_TRACT_48_TEXAS")

# Read in ejscreen data
ejscreen <- st_read(here::here("data", "ejscreen", "EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb"), quiet = TRUE)
```

```{r, warning=TRUE, message=TRUE}
# List of your spatial objects
spatial_objects <- list(building, roads, tile_8_5_07, tile_8_6_07, tile_8_5_16, tile_8_6_16, texas_cens)

# Loop through the list and check CRS
for (i in seq_along(spatial_objects)) {
  if (st_crs(spatial_objects[[1]]) != st_crs(spatial_objects[[i]])) {
    spatial_objects[[i]] <- st_transform(spatial_objects[[i]], crs = st_crs(building))
  } else {
    print(paste("CRS of", names(spatial_objects)[i], "matches!"))
  }
}
```

```{r, fig.width=10, fig.height=8}
# Merge tiles to make one frame 
tile_merge_07 <- merge(tile_8_5_07, tile_8_6_07)
tile_merge_16 <- merge(tile_8_5_16, tile_8_6_16)


# Set the extent to include just Houston 
clip <- rast(xmin= -96.5, xmax = -94.5, ymin = 29, ymax = 30.5, resolution = .3, vals = 1)

# Crop tiles to the settings in the variable clip
tile_merge_07_clip <- crop(tile_merge_07, clip)
tile_merge_16_clip <- crop(tile_merge_16, clip)

# Subtract tile day 16 from tile day 7 to created difference raster mask 
diff_rast_mask <- (tile_merge_07_clip - tile_merge_16_clip)

# Assign NA to locations with a drop of less than 200 nW cm² sr⁻¹ 
diff_rast_mask[diff_rast_mask <= 200] <- NA 

# Vectorize blackout mask with as.polygons and st_as_sf to make it vector data instead of raster
diff_rast_mask_poly <- as.polygons(diff_rast_mask) %>% 
  st_as_sf()

# Use filter to filter for Harris County 
houstin <- ejscreen %>% 
  filter((STATE_NAME == "Texas") & (CNTY_NAME %in% c("Harris County", "Liberty County", "Austin County", "Waller County", "Montgomery County", "Chambers County", "Fort Bend County", "Galveston County", "Brazoria County", "Washington County", "Grimes County", "Burleson County", "Brazos County", "San Jacinto County", "Austin County", "Colorado County", "Matagorda County", "Wharton County", "Jackson County", "Polk County", "Walker County")))

# Map the blackout data
blackout_map <- tm_shape(houstin, 
         bbox = diff_rast_mask_poly) + 
  tm_polygons(fill = "seashell1",
              col = "grey80") + 
  tm_shape(diff_rast_mask_poly) +
  tm_polygons(fill = "brown", 
              alpha = .7,
              border.col = NA) + 
  tm_layout(bg.color = "#E0FFFF") + 
  tm_title(text = "Blackout Areas Houstin, TX",
           fontfamily = "fantasy",
           fontface = "bold",
           position = c("left", "top"))

print(blackout_map)
```

```{r}


```



